const hobbiesInterests = [
    [
        { value: "1", label: "Hiking" },
        { value: "2", label: "Camping" },
        { value: "3", label: "Fishing" },
        { value: "4", label: "Hunting" },
        { value: "5", label: "Rock Climbing" },
        { value: "6", label: "Bird Watching" },
        { value: "7", label: "Kayaking" },
        { value: "8", label: "Canoeing" },
        { value: "9", label: "Surfing" },
        { value: "10", label: "Snowboarding" },
        { value: "11", label: "Skiing" },
        { value: "12", label: "Mountain Biking" },
        { value: "13", label: "Road Biking" },
        { value: "14", label: "Running" },
        { value: "15", label: "Jogging" },
        { value: "16", label: "Trail Running" },
        { value: "17", label: "Paddleboarding" },
        { value: "18", label: "Sailing" },
        { value: "19", label: "Horseback Riding" },
        { value: "20", label: "Gardening" },
        { value: "21", label: "Stargazing" },
        { value: "22", label: "Geocaching" },
        { value: "23", label: "Off-roading" },
        { value: "24", label: "Archery" },
        { value: "25", label: "Skateboarding" },
    ],
    [
        { value: "26", label: "Basketball" },
        { value: "27", label: "Football (American)" },
        { value: "28", label: "Soccer" },
        { value: "29", label: "Baseball" },
        { value: "30", label: "Softball" },
        { value: "31", label: "Volleyball" },
        { value: "32", label: "Tennis" },
        { value: "33", label: "Badminton" },
        { value: "34", label: "Golf" },
        { value: "35", label: "Swimming" },
        { value: "36", label: "Martial Arts" },
        { value: "37", label: "Yoga" },
        { value: "38", label: "Pilates" },
        { value: "39", label: "CrossFit" },
        { value: "40", label: "Weightlifting" },
        { value: "41", label: "Boxing" },
        { value: "42", label: "Wrestling" },
        { value: "43", label: "Cheerleading" },
        { value: "44", label: "Gymnastics" },
        { value: "45", label: "Dance" },
        { value: "46", label: "Ice Hockey" },
        { value: "47", label: "Lacrosse" },
        { value: "48", label: "Cricket" },
        { value: "49", label: "Ultimate Frisbee" },
        { value: "50", label: "Rugby" },
    ],
    [
        { value: "51", label: "Painting" },
        { value: "52", label: "Drawing" },
        { value: "53", label: "Sketching" },
        { value: "54", label: "Sculpting" },
        { value: "55", label: "Pottery" },
        { value: "56", label: "Knitting" },
        { value: "57", label: "Crocheting" },
        { value: "58", label: "Sewing" },
        { value: "59", label: "Quilting" },
        { value: "60", label: "Embroidery" },
        { value: "61", label: "Woodworking" },
        { value: "62", label: "Metalworking" },
        { value: "63", label: "Calligraphy" },
        { value: "64", label: "Photography" },
        { value: "65", label: "Videography" },
        { value: "66", label: "Filmmaking" },
        { value: "67", label: "Acting" },
        { value: "68", label: "Singing" },
        { value: "69", label: "Songwriting" },
        { value: "70", label: "Playing Musical Instruments (Guitar, Piano, Drums, etc.)" },
        { value: "71", label: "Dancing (Ballet, Hip Hop, Salsa, etc.)" },
        { value: "72", label: "Crafting" },
        { value: "73", label: "Jewelry Making" },
        { value: "74", label: "Writing (Poetry, Novels, etc.)" },
        { value: "75", label: "Journaling" },
    ],
    [
        { value: "76", label: "Reading" },
        { value: "77", label: "Watching Movies" },
        { value: "78", label: "Binge-watching" },
        { value: "79", label: "Theater" },
        { value: "80", label: "Opera" },
        { value: "81", label: "Stand-up Comedy" },
        { value: "82", label: "Attending Concerts" },
        { value: "83", label: "Music Festivals" },
        { value: "84", label: "Podcasts" },
        { value: "85", label: "Gaming (Video Games, Board Games, Card Games, etc.)" },
        { value: "86", label: "Puzzle Solving (Crosswords, Sudoku, etc.)" },
        { value: "87", label: "Trivia" },
        { value: "88", label: "Watching Sports" },
        { value: "89", label: "Cosplaying" },
        { value: "90", label: "Collecting (Stamps, Coins, Comics, etc.)" },
        { value: "91", label: "Magic Tricks" },
    ],
    [
        { value: "92", label: "Cooking" },
        { value: "93", label: "Baking" },
        { value: "94", label: "Grilling/BBQ" },
        { value: "95", label: "Mixology" },
        { value: "96", label: "Wine Tasting" },
        { value: "97", label: "Beer Brewing" },
        { value: "98", label: "Coffee Tasting" },
        { value: "99", label: "Tea Tasting" },
        { value: "100", label: "Food Blogging" },
        { value: "101", label: "Trying New Restaurants" },
        { value: "102", label: "Vegetarian/Vegan Cooking" },
    ],
    [
        { value: "103", label: "Traveling" },
        { value: "104", label: "Road Trips" },
        { value: "105", label: "Exploring New Cities" },
        { value: "106", label: "Visiting Museums" },
        { value: "107", label: "Visiting Art Galleries" },
        { value: "108", label: "Attending Festivals" },
        { value: "109", label: "Volunteering" },
        { value: "110", label: "Charity Work" },
        { value: "111", label: "Social Clubs" },
        { value: "112", label: "Book Clubs" },
        { value: "113", label: "Networking Events" },
        { value: "114", label: "Public Speaking" },
        { value: "115", label: "Debate" },
        { value: "116", label: "Language Learning" },
        { value: "117", label: "Cultural Events" },
    ],
    [
        { value: "118", label: "Coding" },
        { value: "119", label: "Robotics" },
        { value: "120", label: "3D Printing" },
        { value: "121", label: "Virtual Reality" },
        { value: "122", label: "Augmented Reality" },
        { value: "123", label: "Building Computers" },
        { value: "124", label: "Electronics" },
        { value: "125", label: "Astronomy" },
        { value: "126", label: "Science Experiments" },
        { value: "127", label: "Drone Flying" },
    ],
    [
        { value: "128", label: "Chess" },
        { value: "129", label: "Strategy Games" },
        { value: "130", label: "Philosophy" },
        { value: "131", label: "History" },
        { value: "132", label: "Archaeology" },
        { value: "133", label: "Anthropology" },
        { value: "134", label: "Psychology" },
        { value: "135", label: "Economics" },
        { value: "136", label: "Politics" },
        { value: "137", label: "Debate" },
        { value: "138", label: "Mathematics" },
        { value: "139", label: "Cryptography" },
        { value: "140", label: "Puzzles" },
    ],
    [
        { value: "141", label: "Bird Watching" },
        { value: "142", label: "Wildlife Photography" },
        { value: "143", label: "Beekeeping" },
        { value: "144", label: "Dog Training" },
        { value: "145", label: "Cat Care" },
        { value: "146", label: "Reptile Keeping" },
        { value: "147", label: "Fish Keeping" },
        { value: "148", label: "Animal Rescue" },
        { value: "149", label: "Farming" },
        { value: "150", label: "Permaculture" },
    ],
    [
        { value: "151", label: "Collecting Antiques" },
        { value: "152", label: "Miniatures" },
        { value: "153", label: "Model Building" },
        { value: "154", label: "Trainspotting" },
        { value: "155", label: "Urban Exploration" },
        { value: "156", label: "Home Improvement" },
        { value: "157", label: "Interior Design" },
        { value: "158", label: "Feng Shui" },
        { value: "159", label: "Meditation" },
        { value: "160", label: "Astrology" },
        { value: "161", label: "Tarot Reading" },
        { value: "162", label: "Numerology" },
        { value: "163", label: "Genealogy" },
        { value: "164", label: "Thrill Seeking" },
        { value: "165", label: "Fandom Activities (Sci-Fi, Fantasy, etc.)" },
        { value: "166", label: "Vlogging" },
        { value: "167", label: "Blogging" },
        { value: "168", label: "Sustainable Living" },
        { value: "169", label: "Zero Waste Lifestyle" },
        { value: "170", label: "Environmental Activism" }
    ],
];

// const hobbiesInterests = [
//     { value: 1, label: "Hiking" },
//     { value: 2, label: "Camping" },
//     { value: 3, label: "Fishing" },
//     { value: 4, label: "Hunting" },
//     { value: 5, label: "Rock Climbing" },
//     { value: 6, label: "Bird Watching" },
//     { value: 7, label: "Kayaking" },
//     { value: 8, label: "Canoeing" },
//     { value: 9, label: "Surfing" },
//     { value: 10, label: "Snowboarding" },
//     { value: 11, label: "Skiing" },
//     { value: 12, label: "Mountain Biking" },
//     { value: 13, label: "Road Biking" },
//     { value: 14, label: "Running" },
//     { value: 15, label: "Jogging" },
//     { value: 16, label: "Trail Running" },
//     { value: 17, label: "Paddleboarding" },
//     { value: 18, label: "Sailing" },
//     { value: 19, label: "Horseback Riding" },
//     { value: 20, label: "Gardening" },
//     { value: 21, label: "Stargazing" },
//     { value: 22, label: "Geocaching" },
//     { value: 23, label: "Off-roading" },
//     { value: 24, label: "Archery" },
//     { value: 25, label: "Skateboarding" },
//     { value: 26, label: "Basketball" },
//     { value: 27, label: "Football (American)" },
//     { value: 28, label: "Soccer" },
//     { value: 29, label: "Baseball" },
//     { value: 30, label: "Softball" },
//     { value: 31, label: "Volleyball" },
//     { value: 32, label: "Tennis" },
//     { value: 33, label: "Badminton" },
//     { value: 34, label: "Golf" },
//     { value: 35, label: "Swimming" },
//     { value: 36, label: "Martial Arts" },
//     { value: 37, label: "Yoga" },
//     { value: 38, label: "Pilates" },
//     { value: 39, label: "CrossFit" },
//     { value: 40, label: "Weightlifting" },
//     { value: 41, label: "Boxing" },
//     { value: 42, label: "Wrestling" },
//     { value: 43, label: "Cheerleading" },
//     { value: 44, label: "Gymnastics" },
//     { value: 45, label: "Dance" },
//     { value: 46, label: "Ice Hockey" },
//     { value: 47, label: "Lacrosse" },
//     { value: 48, label: "Cricket" },
//     { value: 49, label: "Ultimate Frisbee" },
//     { value: 50, label: "Rugby" },
//     { value: 51, label: "Painting" },
//     { value: 52, label: "Drawing" },
//     { value: 53, label: "Sketching" },
//     { value: 54, label: "Sculpting" },
//     { value: 55, label: "Pottery" },
//     { value: 56, label: "Knitting" },
//     { value: 57, label: "Crocheting" },
//     { value: 58, label: "Sewing" },
//     { value: 59, label: "Quilting" },
//     { value: 60, label: "Embroidery" },
//     { value: 61, label: "Woodworking" },
//     { value: 62, label: "Metalworking" },
//     { value: 63, label: "Calligraphy" },
//     { value: 64, label: "Photography" },
//     { value: 65, label: "Videography" },
//     { value: 66, label: "Filmmaking" },
//     { value: 67, label: "Acting" },
//     { value: 68, label: "Singing" },
//     { value: 69, label: "Songwriting" },
//     { value: 70, label: "Playing Musical Instruments (Guitar, Piano, Drums, etc.)" },
//     { value: 71, label: "Dancing (Ballet, Hip Hop, Salsa, etc.)" },
//     { value: 72, label: "Crafting" },
//     { value: 73, label: "Jewelry Making" },
//     { value: 74, label: "Writing (Poetry, Novels, etc.)" },
//     { value: 75, label: "Journaling" },
//     { value: 76, label: "Reading" },
//     { value: 77, label: "Watching Movies" },
//     { value: 78, label: "Binge-watching TV Shows" },
//     { value: 79, label: "Theater" },
//     { value: 80, label: "Opera" },
//     { value: 81, label: "Stand-up Comedy" },
//     { value: 82, label: "Attending Concerts" },
//     { value: 83, label: "Music Festivals" },
//     { value: 84, label: "Podcasts" },
//     { value: 85, label: "Gaming (Video Games, Board Games, Card Games, etc.)" },
//     { value: 86, label: "Puzzle Solving (Crosswords, Sudoku, etc.)" },
//     { value: 87, label: "Trivia" },
//     { value: 88, label: "Watching Sports" },
//     { value: 89, label: "Cosplaying" },
//     { value: 90, label: "Collecting (Stamps, Coins, Comics, etc.)" },
//     { value: 91, label: "Magic Tricks" },
//     { value: 92, label: "Cooking" },
//     { value: 93, label: "Baking" },
//     { value: 94, label: "Grilling/BBQ" },
//     { value: 95, label: "Mixology" },
//     { value: 96, label: "Wine Tasting" },
//     { value: 97, label: "Beer Brewing" },
//     { value: 98, label: "Coffee Tasting" },
//     { value: 99, label: "Tea Tasting" },
//     { value: 100, label: "Food Blogging" },
//     { value: 101, label: "Trying New Restaurants" },
//     { value: 102, label: "Vegetarian/Vegan Cooking" },
//     { value: 103, label: "Traveling" },
//     { value: 104, label: "Road Trips" },
//     { value: 105, label: "Exploring New Cities" },
//     { value: 106, label: "Visiting Museums" },
//     { value: 107, label: "Visiting Art Galleries" },
//     { value: 108, label: "Attending Festivals" },
//     { value: 109, label: "Volunteering" },
//     { value: 110, label: "Charity Work" },
//     { value: 111, label: "Social Clubs" },
//     { value: 112, label: "Book Clubs" },
//     { value: 113, label: "Networking Events" },
//     { value: 114, label: "Public Speaking" },
//     { value: 115, label: "Debate" },
//     { value: 116, label: "Language Learning" },
//     { value: 117, label: "Cultural Events" },
//     { value: 118, label: "Coding" },
//     { value: 119, label: "Robotics" },
//     { value: 120, label: "3D Printing" },
//     { value: 121, label: "Virtual Reality" },
//     { value: 122, label: "Augmented Reality" },
//     { value: 123, label: "Building Computers" },
//     { value: 124, label: "Electronics" },
//     { value: 125, label: "Astronomy" },
//     { value: 126, label: "Science Experiments" },
//     { value: 127, label: "Drone Flying" },
//     { value: 128, label: "Chess" },
//     { value: 129, label: "Strategy Games" },
//     { value: 130, label: "Philosophy" },
//     { value: 131, label: "History" },
//     { value: 132, label: "Archaeology" },
//     { value: 133, label: "Anthropology" },
//     { value: 134, label: "Psychology" },
//     { value: 135, label: "Economics" },
//     { value: 136, label: "Politics" },
//     { value: 137, label: "Debate" },
//     { value: 138, label: "Mathematics" },
//     { value: 139, label: "Cryptography" },
//     { value: 140, label: "Puzzles" },
//     { value: 141, label: "Bird Watching" },
//     { value: 142, label: "Wildlife Photography" },
//     { value: 143, label: "Beekeeping" },
//     { value: 144, label: "Dog Training" },
//     { value: 145, label: "Cat Care" },
//     { value: 146, label: "Reptile Keeping" },
//     { value: 147, label: "Fish Keeping" },
//     { value: 148, label: "Animal Rescue" },
//     { value: 149, label: "Farming" },
//     { value: 150, label: "Permaculture" },
//     { value: 151, label: "Collecting Antiques" },
//     { value: 152, label: "Miniatures" },
//     { value: 153, label: "Model Building" },
//     { value: 154, label: "Trainspotting" },
//     { value: 155, label: "Urban Exploration" },
//     { value: 156, label: "Home Improvement" },
//     { value: 157, label: "Interior Design" },
//     { value: 158, label: "Feng Shui" },
//     { value: 159, label: "Meditation" },
//     { value: 160, label: "Astrology" },
//     { value: 161, label: "Tarot Reading" },
//     { value: 162, label: "Numerology" },
//     { value: 163, label: "Genealogy" },
//     { value: 164, label: "Thrill Seeking (Skydiving, Bungee Jumping, etc.)" },
//     { value: 165, label: "Fandom Activities (Sci-Fi, Fantasy, etc.)" },
//     { value: 166, label: "Vlogging" },
//     { value: 167, label: "Blogging" },
//     { value: 168, label: "Sustainable Living" },
//     { value: 169, label: "Zero Waste Lifestyle" },
//     { value: 170, label: "Environmental Activism" }
// ];



export default hobbiesInterests;
